### PR TITLE
Bug Fix: Supported Disabled option

### LINKED ISSUE #1333: Conduit: data pruning error
Setting the interval to 0 does not disable the delete task.

Using this config:
```
  delete-task:
    # Rounds to keep
    rounds: 100000
    # Interval used to prune the data. The values can be -1 to run at startup,
    # 0 to disable or N to run every N rounds.
    interval: 0
```

Conduit exited with an error:
```
{"__type":"exporter","_name":"postgresql","level":"fatal","msg":"DeleteLoop(): unsupported interval value 0","time":"2022-11-17T17:16:55Z"}
```

### PR DESCRIPTION
**Pull request by AlgoStephenAkiki**
Resolves #1333 

Supports the disabled value for the PruneConfigurations "Interval" config

### CODE REVIEW

File: conduit/plugins/exporters/postgresql/util/prune.go [hunk 1]
```diff
@@ -59,6 +59,16 @@ func MakeDataManager(ctx context.Context, cfg *PruneConfigurations, db idb.Index
 func (p *postgresql) DeleteLoop(wg *sync.WaitGroup, nextRound *uint64) {
 
 	defer wg.Done()
+	// If the interval is disabled
+	if p.config.Interval == disabled {
+		// A helpful warning to say that despite a number of rounds being above 0
+		// data pruning isn't going to occur
+		if p.config.Rounds > 0 {
+			p.logger.Warnf("DeleteLoop(): Round value was above 0 (%d) but interval was disabled. No data pruning will occur.", p.config.Rounds)
+		}
```
Comment (winder) [inline conduit/plugins/exporters/postgresql/util/prune.go:68]: Nice touch

**Review by winder — APPROVED** [review]

**Review by Eric-Warehime — APPROVED** [review]
