### PR TITLE
Changed configuration for postgres

### LINKED ISSUE #826: Configurable Postgres Connection Pool Size
## Problem

It is possible to exhaust the DB connection handles, when that happens strange errors and unexpected behavior may occur. For example `FATAL: the database system is in recovery mode (SQLSTATE 57P03)`.

## Solution

Provide an indexer setting for configuring the pool size so that the local connection pool is exhausted before the connection pool. The connection pool is currently configured in the `OpenPostgres` function, we would replace `pgxpool.Connect` with `pgxpool.ConnectConfig`, and supply the `MaxConns` setting.

## Dependencies

No

### PR DESCRIPTION
**Pull request by AlgoStephenAkiki**
Resolves #826 

Changed database interface to include options and pushed implementation into postgres only.

### CODE REVIEW

File: cmd/algorand-indexer/daemon.go [hunk 1]
```diff
@@ -34,6 +34,8 @@ var (
 	tokenString      string
 	writeTimeout     time.Duration
 	readTimeout      time.Duration
+	maxConn          int32
```
Comment (shiqizng) [inline cmd/algorand-indexer/daemon.go:37]: should these be uint32 to disallow negative values?

Comment (AlgoStephenAkiki) [reply cmd/algorand-indexer/daemon.go:37]: I chose int32 because the postgres config units are int32...Should I change them here and cast them when creating the Postgres config?

Comment (winder) [reply cmd/algorand-indexer/daemon.go:37]: Unless there's a reason to allow negative values, I think it would be better to use uint32 here and let the flag parser enforce the negative bounds checking for us.

Sometimes interfaces use uint32 to avoid casts when using other built-ins... for example:
```
if len(connections) >= maxConn {
    ...
}
```

**Review by shiqizng — DISMISSED** [review]

File: cmd/algorand-indexer/daemon.go [hunk 2]
```diff
@@ -141,6 +145,7 @@ func init() {
 	daemonCmd.Flags().StringVarP(&metricsMode, "metrics-mode", "", "OFF", "configure the /metrics endpoint to [ON, OFF, VERBOSE]")
 	daemonCmd.Flags().DurationVarP(&writeTimeout, "write-timeout", "", 30*time.Second, "set the maximum duration to wait before timing out writes to a http response, breaking connection")
 	daemonCmd.Flags().DurationVarP(&readTimeout, "read-timeout", "", 5*time.Second, "set the maximum duration for reading the entire request")
+	daemonCmd.Flags().Uint32VarP(&maxConn, "max-conn", "", 4, "set the maximum connections allowed in the connection pool")
```
Comment (winder) [inline cmd/algorand-indexer/daemon.go:148]: 4 is the default? Seems small, I think making it optional and setting it to 0 would be better.

Please update the readme, we should mention that we recommend people should set this to a number smaller than their Postgres server's configuration.

**Review by winder — CHANGES_REQUESTED** [review]
Looks good, just missing a README update and a test. Since this is all encapsulated in `OpenPostgres` the unit tests should be able to exercise the connection pool error.

File: cmd/algorand-indexer/daemon.go (hunk 2 above)
Comment (AlgoStephenAkiki) [reply cmd/algorand-indexer/daemon.go:148]: 4 is the default number of the postgres pool but we can make it optional.

**Review by winder — CHANGES_REQUESTED** [review]
This needs a test, everything else looks good.

File: cmd/algorand-indexer/daemon.go [hunk 3]
```diff
@@ -141,6 +145,7 @@ func init() {
 	daemonCmd.Flags().StringVarP(&metricsMode, "metrics-mode", "", "OFF", "configure the /metrics endpoint to [ON, OFF, VERBOSE]")
 	daemonCmd.Flags().DurationVarP(&writeTimeout, "write-timeout", "", 30*time.Second, "set the maximum duration to wait before timing out writes to a http response, breaking connection")
 	daemonCmd.Flags().DurationVarP(&readTimeout, "read-timeout", "", 5*time.Second, "set the maximum duration for reading the entire request")
+	daemonCmd.Flags().Uint32VarP(&maxConn, "max-conn", "", 0, "set the maximum connections allowed in the connection pool")
```
Comment (winder) [inline cmd/algorand-indexer/daemon.go:148]: Is this accurate?
```suggestion
	daemonCmd.Flags().Uint32VarP(&maxConn, "max-conn", "", 0, "set the maximum connections allowed in the connection pool, if the maximum is reached subsequent connections will be queued and wait until a connection becomes available, or timeout according to the read-timeout setting")
```

Comment (AlgoStephenAkiki) [reply cmd/algorand-indexer/daemon.go:148]: The subsequent connections I believe will block, which is a little different than queued.  But the rest seems accurate.

Comment (winder) [reply cmd/algorand-indexer/daemon.go:148]: "queued and wait" is kinda the same thing as block? How about just saying wait?

Comment (AlgoStephenAkiki) [reply cmd/algorand-indexer/daemon.go:148]: Sure

File: README.md [hunk 4]
```diff
@@ -117,12 +117,19 @@ When `--token your-token` is provided, an authentication header is required. For
...
 | ------- | ----------- |
 | ON      | Metrics for each REST endpoint in addition to application metrics. |
 | OFF     | No metrics endpoint. |
 | VERBOSE | Separate metrics for each combination of query parameters. This option should be used with caution, there are many combinations of query parameters which could cause extra memory load depending on usage patterns. |
 
+## Connection Pool Settings
+
+One can set the maximum number of connections allowed in the local connection pool by using the `--max-conn` setting.  It is recommended to set this number to be below the database server connection pool limit.
+ 
+If the maximum number of connections/active queries is reached, subsequent connections will wait until a connection becomes available, or timeout according to the read-timeout setting
```
Comment (winder) [inline README.md:131]:
```suggestion
If the maximum number of connections/active queries is reached, subsequent connections will wait until a connection becomes available, or timeout according to the read-timeout setting.
```

**Review by winder — APPROVED** [review]
