### PR TITLE
Conduit: ensure thread safety across multiple loggers.

### LINKED ISSUE #1245: Conduit: Duplicate logger output
When starting Conduit with no arguments, there are duplicate error outputs:

```
{"__type":"Conduit","_name":"main","level":"info","msg":"Data Directory:  ","time":"2022-09-16T15:50:51-04:00"}
Error: supplied data directory was empty
ERRO[0000] supplied data directory was empty
```

Some initial investigation:
```
The first line is us trying to log the config after we've loaded it: https://github.com/algorand/indexer/blob/conduit/cmd/conduit/main.go#L69

The Error message is the validity function finding the data directory in the config empty: https://github.com/algorand/indexer/blob/conduit/conduit/config.go#L27

And the third line is probably from https://github.com/algorand/indexer/blob/conduit/cmd/conduit/main.go#L122
Seems like we've got a bunch of duplicate logs of the same thing I guess? Since we are using a logger initialized in the init function we should probably always be using that.
```

We are also using `RunE` instead of `Run` in conduit, which is probably where one of the error outputs comes from. But it is not clear to me why the format is different.

### PR DESCRIPTION
**Pull request by AlgoStephenAkiki**
Resolves #1245 
    
 Adds a multi-threaded logger instance for conduit usage

### CODE REVIEW

File: importers/importer.go [hunk 1]
```diff
@@ -17,7 +17,7 @@ type Importer interface {
 	// Init will initialize each importer with a given config. This config will contain the Unmarhsalled config file specific to this plugin.
 	// It is called during initialization of an importer plugin such as setting up network connections, file buffers etc.
 	// Importers will also be responsible for returning a valid Genesis object pointer
-	Init(ctx context.Context, cfg plugins.PluginConfig, logger *logrus.Logger) (*bookkeeping.Genesis, error)
+	Init(ctx context.Context, cfg plugins.PluginConfig, logger *loggers.MT) (*bookkeeping.Genesis, error)
```
Comment (winder) [inline importers/importer.go:20]: Could you help me understand why the new interface is needed here? Does the plugin writer need to know that we've done something special with the logger?

File: loggers/loggers.go [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+
+// LoggerManager a manager that can produce loggers that are synchronized internally
+type LoggerManager struct {
+	internalWriter ThreadSafeWriter
+}
+
+// AdaptLogger will take a logger instance and wrap it for synchronization
+func AdaptLogger(log *log.Logger) *LoggerManager {
+	return MakeLoggerManager(log.Out)
+}
```
Comment (winder) [inline loggers/loggers.go:23]: I don't think you need this function:
* If `MakeLogger` returns log.Logger, then you don't need to change all the interfaces.
* Now you don't need `MakeLoggerManager` to wrap the writer, all the tests could continue using `log.New`.

File: loggers/loggers.go [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+			Mutex:  &sync.Mutex{},
+		},
+	}
+}
+
+// ThreadSafeWriter a struct that implements io.Writer in a threadsafe way
+type ThreadSafeWriter struct {
+	Writer io.Writer
+	Mutex  *sync.Mutex
+}
```
Comment (winder) [inline loggers/loggers.go:46]: Are there any tests that could be written for this? i.e. Take a logger that uses the ThreadSafeWriter and fire a bunch of logs at it. Maybe also a good opportunity to write a very large log message and see that it isn't broken into parts?

File: loggers/loggers.go [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+
+// Write writes p bytes with the mutex
+func (w ThreadSafeWriter) Write(p []byte) (n int, err error) {
+	w.Mutex.Lock()
+	defer w.Mutex.Unlock()
+	return w.Writer.Write(p)
+}
```
Comment (winder) [inline loggers/loggers.go:53]: that should do it! :+1:

File: loggers/loggers.go (hunk 3 above)
Comment (AlgoStephenAkiki) [reply loggers/loggers.go:41]: See updated test

File: loggers/loggers_test.go [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+		go func() {
+			// Sleep a random number of milliseconds before and after to test
+			// that creating a logger doesn't affect thread-safety
+			time.Sleep(time.Duration(rand.Intn(50)) * time.Millisecond)
+			l := lMgr.MakeLogger()
+			l.SetFormatter(&log.JSONFormatter{
+				// We want to disable timestamps to stop logrus from sorting our output
+				DisableTimestamp: true,
+			})
+			time.Sleep(time.Duration(rand.Intn(50)) * time.Millisecond)
```
Comment (winder) [inline loggers/loggers_test.go:50]: One trick for starting all of the loggers at the same time is to have them all wait on the same wait group. That you mark as Done once the goroutines have been created

File: loggers/loggers_test.go [hunk 6]
```diff
@@ -0,0 +1,89 @@
...
+	"testing"
+	"time"
+
+	log "github.com/sirupsen/logrus"
+	"github.com/stretchr/testify/assert"
+)
+
+type FakeIoWriter struct {
+	// A list of strings that represent ints
+	ListOfInts []string
```
Comment (winder) [inline loggers/loggers_test.go:17]: Should you allocate the array to the expected size?

**Review by winder — APPROVED** [review]
Just had a couple minor comments for you to consider. Looks good.

File: loggers/loggers_test.go (hunk 5 above)
Comment (AlgoStephenAkiki) [reply loggers/loggers_test.go:50]: I want to make sure that they don't start at the same time though.  I want to make sure that making the logger doesn't affect thread-safety.

File: loggers/loggers_test.go (hunk 6 above)
Comment (AlgoStephenAkiki) [reply loggers/loggers_test.go:17]: The slice is easier from a testing perspective since I don't have to keep track of the latest entry (I can simply append).  Plus I dont think the performance is that bad with the current test.  We can always change it if we want to later.

**Review by shiqizng — APPROVED** [review]
