### PR TITLE
Bug Fix: Fix auto-loading search

### LINKED ISSUE #1064: Hot Fix: Fix auto loading search and config loading errors
1. Auto searching of configurations can clash with supplied data directory configurations.  To simplify this, providing configurations in both the auto-searched directories and data directory will result in an error.

2. Because the config file load code was moved around, the command that ties the go-lang variables to the read-in config file was not positioned correctly.  Once fixed the read-in configuration will bind with the variables correctly.

### PR DESCRIPTION
**Pull request by AlgoStephenAkiki**
Resolves #1064

1. Auto searching of configurations can clash with supplied data directory configurations.  To simplify this, providing configurations in both the auto-searched directories and data directory will result in an error.

2. Because the config file load code was moved around, the command that ties the go-lang variables to the read-in config file was not positioned correctly.  Once fixed the read-in configuration will bind with the variables correctly.

This code was manually tested by enabling parameters via the data
directory config and validating that certain endpoints were
enabled/disabled.

### CODE REVIEW

**Review by algobarb — APPROVED** [review]
Reviewed the use cases and the documentation/code changes. It all looks good! Thanks for the changes, @AlgoStephenAkiki !

File: cmd/algorand-indexer/daemon.go [hunk 1]
```diff
@@ -343,7 +344,14 @@ func makeOptions() (options api.ExtraOptions) {
...
 			panic(exit{1})
 		}
+
+		if len((*potentialDisabledMapConfig).Data) == 0 {
+			logger.Infof("NOTICE: All parameters are enabled since the provided parameter configuration file (%s) is empty.", suppliedAPIConfigFile)
+		}
+
 		options.DisabledMapConfig = potentialDisabledMapConfig
+	} else {
+		logger.Infof("NOTICE: Enable all parameters flag is set to: %v", enableAllParameters)
```
Comment (winder) [inline cmd/algorand-indexer/daemon.go:354]: In the log file, we can label the severity in a structured way.
```suggestion

		if len((*potentialDisabledMapConfig).Data) == 0 {
			logger.Warnf("All parameters are enabled since the provided parameter configuration file (%s) is empty.", suppliedAPIConfigFile)
		}

		options.DisabledMapConfig = potentialDisabledMapConfig
	} else {
		logger.Warnf("Enable all parameters flag is set to: %v", enableAllParameters)
```

Comment (AlgoStephenAkiki) [reply cmd/algorand-indexer/daemon.go:354]: The second one is more of a informational one, but I can change the first one to a warning.

**Review by winder — APPROVED** [review]
